[sg fromlist] net: lwm2m: device object: Fix coverage compatibility
Starting with b1d24e425c3a30cdf1aed3c54c25a2518061accc (net: lwm2m:
device object: optionally store error list in settings), it was no
longer possible to build the code with coverage enabled when the
settings subsystem was disabled.

The build would fail with an error like this:

> subsys/net/lib/lwm2m/lwm2m_obj_device.c:262: undefined reference to
> `settings_name_steq'

This fixes #70923.

Upstream: https://github.com/lemonbeat/lb_radio/pull/359

Signed-off-by: Reto Schneider <reto.schneider@husqvarnagroup.com>
(cherry picked from commit e6d2394499aded403a34d5c62e9dfbb01c6a52fd)