cmake: sca: cppcheck: Use Clang frontend
This does not yet work because cppcheck does not pass '-include
build/zephyr/include/generated/zephyr/autoconf.h' to clang.

The following yields 'error: use of undeclared identifier
'CONFIG_BOARD_TARGET'', followed by a very verbose AST dump and an
build/sca/cppcheck/index.html file that contains zero findings:

$ west build --pristine --board sim3u1xx_dk zephyr/samples/hello_world \
 -- -DZEPHYR_SCA_VARIANT=cppcheck

While the command above fails, it informs about the way clang gets
called. Adding "-include .../zephyr/autoconf.h" to it properly dumps the
AST.

$ clang -fsyntax-only -Xclang -ast-dump -fno-color-diagnostics -x c \
  -std=c99 -Ibuild/zephyr/include/generated/zephyr/ -Izephyr/include/ \
  -Ibuild/zephyr/include/generated/ -Izephyr/soc/silabs/ \
  -Izephyr/soc/silabs/common/./ -Izephyr/soc/silabs/silabs_sim3/sim3u/ \
  -Imodules/hal/cmsis/CMSIS/Core/Include/ -Izephyr/modules/cmsis/ \
  -Imodules/hal/silabs/si32/si32Hal/sim3u1xx/ \
  -Imodules/hal/silabs/si32/si32Hal/SI32_Modules/ \
  -Izephyr/lib/libc/common/include -D__cppcheck__=1 -DKERNEL=1 \
  -DK_HEAP_MEM_POOL_SIZE=0 -DPICOLIBC_LONG_LONG_PRINTF_SCANF=1 \
  -D__LINUX_ERRNO_EXTENSIONS__=1 -D__PROGRAM_START=1 -D__ZEPHYR__=1 \
  zephyr/samples/hello_world/src/main.c -include \
  build/zephyr/include/generated/zephyr/autoconf.h

The result is the same for clang-14 as well as for clang-19.